name: Hello World
author: Kafui Alordo
description: Hello World Action
inputs:
  who-to-greet:
    description: "Who to greet"
    required: true
    default: Kafui
outputs:
  time:
    description: "The greeting time"
runs:
  using: "docker"
  image: "Dockerfile"
  args:
    - ${{ inputs.who-to-greet }}
