on: push
jobs:
  test-action:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Send s Slack Message
        uses: ./.github/actions/slack
        with:
          slack_webhook: ${{ secrets.SLACK_WEBHOOK }}
          message: Hello Slack
      - uses: ./.github/actions/issue
        id: issue
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          title: Title
          body: Body
          assignees: |
            kafui4k
            kafui-alordo
      - run: |
          echo ${{ steps.issue.outputs.issue }}
      - uses: ./.github/actions/hello-docker
        id: hello
        with:
          who-to-greet: "World"
      - run: |
          echo "Time: ${{ steps.hello.outputs.time }}"
          echo $HELLO
