name: "Open GitHub Issue"
author: kafui4k
description: "Opens a GitHub issue"
inputs:
  token:
    description: "GitHub Token"
    required: true
  title:
    description: "Issue Title"
    required: true
  body:
    description: "Issue Body"
  assignees:
    description: "Issue Assignees"
outputs:
  issue: # id of the output
    description: "The issue object as a json string"
runs:
  using: "node12"
  main: "dist/index.js"
